### ISSUE TITLE
Some thoughts on DRAM throughput benchmarking

### ISSUE THREAD

**Issue by psalz** [bcosenza/sycl-bench#25]
As previously discussed, I think that the current implementation of the [DRAM microbenchmark](https://github.com/bcosenza/sycl-bench/blob/fe43374b14b85225febbaea51ad16df40b0c9b7f/micro/pattern_DRAM.cpp) is not ideal, *if* our goal is to simply measure throughput. The benchmark is currently based on the paper "GPGPU Power Modeling for Multi-Domain Voltage-Frequency Scaling" (Guerreiro18), in which they used it to characterize the power consumption of GPUs when stressing device memory. However, the kernel itself doesn't just do a memory copy, but also includes a parameter `N` to introduce a certain level of arithmetic intensity. I'm not certain why they have that in there, but I would assume they have their reasons. For us however this means adding another dimension to the benchmark, which makes it harder to evaluate and compare results.

To further complicate things, the actual implementation of the DRAM benchmark used in Guerreiro18, which can be found on GitHub ([here](https://github.com/hpc-ulisboa/gpupowermodel/blob/babdfe88f3e58192fff14d843a2887534378d4cc/v1.0_HPCA2018/microbenchmarks/DRAM/dram.cu#L63)), appears to be completely different. In this version, the arithmetic operations are gone, and the kernel mostly consists of copy instructions. However, it still does some strange things I'm not entirely clear about.

Here's my SYCL implementation of this kernel:
```cpp
cgh.parallel_for<DRAMKernel>(global_size, [=](s::id<1> gid) {
  for(size_t j = 0; j < COPY_ITERATIONS; j += UNROLL_ITERATIONS) {
    for(size_t i = 0; i < UNROLL_ITERATIONS; ++i) {
      DataT r0 = in[gid[0] + STRIDE * i];
      out[gid[0] + STRIDE * i] = r0;
    }
  }
});
```

As you can see, since the loop variable `j` is not being used inside the loop body, this kernel repeatedly copies the same chunk of memory from one buffer into the other; by default `COPY_ITERATIONS` is 1024. In each iteration `UNROLL_ITERATIONS` (default 32) copies are made. To allow for memory coalescing, each thread accesses the buffer based linearly on its global id. Each subsequent copy is offset by a multiple of `STRIDE`. This parameter is sensitive to cache sizes: If chosen too small, caching can occur. In the implementation of Guerreiro18, they use an offset of `64 * 1024`, and profiling reveals a 0% L2 hit rate on my GTX 2070. If I change this to `32 * 1024` however, I already get a 11% L2 hit rate. How large this stride has to be exactly depends on the number of work items, cache sizes and so on. All in all, this version of the benchmark essentially introduces three additional parameters, greatly increasing its complexity, without a clear benefit.

Furthermore, in order to achieve the highest throughput with this benchmark, it weirdly [needs to be compiled](https://github.com/hpc-ulisboa/gpupowermodel/blob/babdfe88f3e58192fff14d843a2887534378d4cc/v1.0_HPCA2018/microbenchmarks/DRAM/Makefile#L11) without any assembly-level optimizations (by passing `-O0` to `ptxas`). This is of course hard to replicate with hipSYCL, and my SYCL implementation of Guerreiro18 thus also only achieves around ~300 GiB/s, i.e., 67% of the GTX 2070's 448 GiB/s theoretical maximum. This is a bit less than the CUDA version achieves *with* optimizations (311 GiB/s), and substantially less than it when compiled *without* optimizations (325 GiB/s).

Long story short, instead of implementing Guerreiro18, I would suggest to instead go for the simplest possible memcopy kernel, i.e.:

``` cpp
cgh.parallel_for<DRAMKernel>(global_size, [=](s::id<1> gid) {
  out[gid] =  in[gid];
});
```

With this, I'm able to get ~358 GiB/s, which is about 80% of the theoretical maximum, and probably quite close to what we can reasonably expect to achieve.

Note that to get good results, the buffer size needs to be large enough, i.e. at least several hundred megabytes. If we do a plain mapping of `--size` to buffer size, this means that the specified sizes need to be rather large. For example I used `--size=939524096` (which equals 3.5 GiB).

This is of course quite a large number, and a much larger size than many other benchmarks can support (if e.g. it is used as the range in both dimensions of a 2D buffer). One possible solution would be to always multiply the size by some fixed factor, e.g. 1024. However, I generally feel like the mapping of the `--size` parameter to the actual workload is too arbitrary already. It might be convenient for running lots of benchmarks in batch, but in reality I think we'll have to hand tune these values (as well as any additional parameters a benchmark might have) for each individual platform anyways. I'm thus thinking whether maybe having individual parameters for each benchmark would make more sense (e.g. having a `buffer-size=` for this one).

In the same vein, having the ability to compute custom metrics would also be great. For example, it would be cool if this benchmark could actually print its achieved throughput, instead of having to manually compute it.

What do you guys think?

**Comment by illuhad** [comment]
I agree with your analysis. Your proposal is much closer to the classical stream workload. For measuring throughput, I think we should rather follow stream.

> This is of course quite a large number, and a much larger size than many other benchmarks can support (if e.g. it is used as the range in both dimensions of a 2D buffer). One possible solution would be to always multiply the size by some fixed factor, e.g. 1024. However, I generally feel like the mapping of the --size parameter to the actual workload is too arbitrary already. It might be convenient for running lots of benchmarks in batch, but in reality I think we'll have to hand tune these values (as well as any additional parameters a benchmark might have) for each individual platform anyways. I'm thus thinking whether maybe having individual parameters for each benchmark would make more sense (e.g. having a buffer-size= for this one).

The `run-suite` script starts with a very small `--size` parameter (I think something like 64) and then doubles the problem size until the runtime has achieved a minimum runtime that is determined by the test profile in `run-suite`. I image this could already work well for many cases. If this is not the case here, the test profiles can override the tested problem sizes for individual benchmarks. We could simply edit the test profile to start with larger values if necessary.

> In the same vein, having the ability to compute custom metrics would also be great. For example, it would be cool if this benchmark could actually print its achieved throughput, instead of having to manually compute it.

Yes, I agree. The main challenge is that the benchmarks are individual applications, that don't know which results the other benchmarks will emit to the csv file. If the benchmarks emit different columns to the csv, this prevents a correct formatting. A solution could be adding a standard field for all benchmarks that will be present in the result of every benchmark, say, `metric`, and benchmarks can choose to implement this or return `N/A`, similar to the verification.

**Comment by psalz** [comment]
> Yes, I agree. The main challenge is that the benchmarks are individual applications, that don't know which results the other benchmarks will emit to the csv file. If the benchmarks emit different columns to the csv, this prevents a correct formatting. A solution could be adding a standard field for all benchmarks that will be present in the result of every benchmark, say, `metric`, and benchmarks can choose to implement this or return `N/A`, similar to the verification.

That could work, yes. It is of course a bit limiting and not very descriptive. Hypothetically, if the various benchmarks were to emit additional metrics/columns -- how useful is it really to have all results for all benchmarks in a single file? Couldn't we just generate separate CSVs for each executable?

Additionally, to compute e.g. throughput, the benchmark would need to have access to the timing results, which, given the current plugin/hook architecture seems a bit messy. Maybe timing should be considered a "core" functionality of the framework instead, much like verification?

**Comment by illuhad** [comment]
> That could work, yes. It is of course a bit limiting and not very descriptive. Hypothetically, if the various benchmarks were to emit additional metrics/columns -- how useful is it really to have all results for all benchmarks in a single file? Couldn't we just generate separate CSVs for each executable?

The `run-suite` script invokes each benchmark a dozen times with different combinations of problem size and local size, so we would have a looot of very small csv files, each with only 1 or a couple rows. For every meaningful analysis, those files would need to be aggregated into one file again anyway. It could be done, but it won't be pretty I think.

> Additionally, to compute e.g. throughput, the benchmark would need to have access to the timing results, which, given the current plugin/hook architecture seems a bit messy. Maybe timing should be considered a "core" functionality of the framework instead, much like verification?

Hm. Good point. There may be more metrics than just bandwidth that require access to one or multiple measurements (e.g. once we can measure power consumption, flops/s/watt). This makes me think that maybe metrics that represent transformations of actual measurements should maybe better be implemented in a post processing step (e.g. in `run-suite`) for the most flexibility?

**Comment by sudansohan** [comment]
> The `run-suite` script invokes each benchmark a dozen times with different combinations of problem size and local size, so we would have a looot of very small csv files, each with only 1 or a couple rows. For every meaningful analysis, those files would need to be aggregated into one file again anyway. It could be done, but it won't be pretty I think.
Do we need so many different configurations? If we can restrict the number of configurations, then it will not be that messy in one CSV file. For example, we do not need to vary the problem size and local size for every experiment.

**Comment by psalz** [comment]
> Hm. Good point. There may be more metrics than just bandwidth that require access to one or multiple measurements (e.g. once we can measure power consumption, flops/s/watt). This makes me think that maybe metrics that represent transformations of actual measurements should maybe better be implemented in a post processing step (e.g. in `run-suite`) for the most flexibility?

The problem I see with this is that e.g. in this case, for DRAM bandwidth, we also need to know the amount of bytes copied. If we go with the mapping from `--size` to 1/2/3D ranges as you proposed on my PR, the number of bytes might depend on that parameter, the dimensionality of the kernel *and* the data type being copied. So either we have the benchmark log this information somewhere (coming back to the issue of per-benchmark metrics), or we hardcode this somehow into `run-suite`, which seems like a bad idea to me.

**Comment by psalz** [comment]
> The `run-suite` script invokes each benchmark a dozen times with different combinations of problem size and local size, so we would have a looot of very small csv files, each with only 1 or a couple rows. For every meaningful analysis, those files would need to be aggregated into one file again anyway. It could be done, but it won't be pretty I think.

Since the script knows which runs belong to the same benchmark, it could just concatenate those outputs into a single CSV. Then we'd have one file per benchmark - that sounds manageable to me.

**Comment by psalz** [comment]
Closing this as we have merged the simpler version of the DRAM benchmark in #26 and added throughput metrics in #30. Thanks everyone!
