### ISSUE TITLE
Questions about the single kernel set

### ISSUE THREAD

**Issue by jinz2014** [bcosenza/sycl-bench#39]
[  3%] Building CXX object CMakeFiles/sobel7.dir/single-kernel/sobel7.cpp.o
Unsupported kernel parameter type
UNREACHABLE executed at /home/cc/sycl_workspace/llvm/clang/lib/Sema/SemaSYCL.cpp:1039!

**Comment by illuhad** [comment]
So, you are using LLVM SYCL? This looks like a lambda capture issue inside LLVM SYCL. I think I have seen some patches recently that supposedly should fix array captures, so maybe you just have to update your installation. With that said, the code in question compiles cleanly with hipSYCL and ComputeCpp, so it's unlikely to be an issue inside sycl-bench.

**Comment by jinz2014** [comment]
Thanks for your comments.
