### ISSUE TITLE
use of undeclared identifier 'device_selector'

### ISSUE THREAD

**Issue by jinz2014** [bcosenza/sycl-bench#40]
In file included from /home/cc/sycl-bench/include/common.h:14:
/home/cc/sycl-bench/include/command_line.h:244:8: error: use of undeclared identifier 'device_selector'
    if(device_selector != "gpu") {

**Comment by illuhad** [comment]
I think that's a typo, it should say `device_type` instead of `device_selector`. With that said, the error occurs at an LLVM SYCL CUDA section. Support for LLVM SYCL in general and LLVM SYCL CUDA backend in particular is still experimental in sycl-bench. We do not claim that this is ready yet ;)

**Comment by jinz2014** [comment]
Thanks for your fix.
